// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh0lZMslNgukDZ9-t5b5039_SpdOBixlw',
    appId: '1:491498573135:web:28d886d0911ef11a5a493a',
    messagingSenderId: '491498573135',
    projectId: 'recipes-cc5b3',
    authDomain: 'recipes-cc5b3.firebaseapp.com',
    storageBucket: 'recipes-cc5b3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs9y-stvsEyFXDcQ2Q2PHRMK08NIYGH2M',
    appId: '1:491498573135:android:28107064ffaf70435a493a',
    messagingSenderId: '491498573135',
    projectId: 'recipes-cc5b3',
    storageBucket: 'recipes-cc5b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALT7AhglWszjt5WDp8--V-HJuI22ILI10',
    appId: '1:491498573135:ios:28a43a837894fabe5a493a',
    messagingSenderId: '491498573135',
    projectId: 'recipes-cc5b3',
    storageBucket: 'recipes-cc5b3.appspot.com',
    iosClientId: '491498573135-hmv1jl49tpqndl8jk9ghe7ki61jqi141.apps.googleusercontent.com',
    iosBundleId: 'com.example.labactivity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALT7AhglWszjt5WDp8--V-HJuI22ILI10',
    appId: '1:491498573135:ios:28a43a837894fabe5a493a',
    messagingSenderId: '491498573135',
    projectId: 'recipes-cc5b3',
    storageBucket: 'recipes-cc5b3.appspot.com',
    iosClientId: '491498573135-hmv1jl49tpqndl8jk9ghe7ki61jqi141.apps.googleusercontent.com',
    iosBundleId: 'com.example.labactivity',
  );
}
